definitions:
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      password:
        type: string
      user_id:
        type: string
      user_number:
        type: string
      user_role:
        type: string
      username:
        type: string
      usersurname:
        type: string
    type: object
  models.UserReq:
    properties:
      email:
        type: string
      otp:
        type: string
      password:
        type: string
      user_number:
        type: string
      user_role:
        type: string
      username:
        type: string
      usersurname:
        type: string
    type: object
info:
  contact: {}
paths:
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user with the provided details
      parameters:
      - description: User object to create
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new user
      tags:
      - user
swagger: "2.0"
